### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by heyarny** [bryceredd/RFQuiltLayout#38]
Anyone know of equivalent project for Android using RecyclerView?
It must not use any pre-defined patterns.
RFQuiltLayout is using bin-packing algorithm, isn't it?

**Comment by Ying1986** [comment]
@heyarny 
I have found you post this issue as task on upwork.

I can port this to android.
Thank you.

**Comment by heyarny** [comment]
@Ying1986 please message me there and lets talk

**Comment by Ying1986** [comment]
my email is yingyingwang1986@hotmail.com

**Comment by Ying1986** [comment]
@heyarny 

I have the experience to use RFQuiltLayout  on iOS project.
https://www.dropbox.com/s/uatlr177yb9mgwu/RFQuitLayout.png?dl=0

**Comment by heyarny** [comment]
@Ying1986 please stop messaging me here about the job. Thanks

**Comment by bryceredd** [comment]
@heyarny try https://github.com/jacobmoncur/QuiltViewLibrary
